# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      # - linux
      # - windows
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
    - -s -w -X main.version={{.Version}}
archives:
  - replacements:
      darwin: Darwin
      # linux: Linux
      # windows: Windows
      # 386: i386
      # amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy
brews:
  - tap:
      owner: wtait1
      name: homebrew-brews
    folder: Formula
    homepage: https://github.com/wtait1/ddf
    description: CLI tool to De-Duplicate Files
    test: |
      system "#{bin}/ddf -v"
